name: Tests

on:
  push:
    branches:
      - "**"
    pull_request:
      branches: [main]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, '8.0', 8.1, 8.2]
        laravel: [6.*, 7.*, 8.*, 9.*, 10.*]
        os: [ubuntu-latest]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*

        exclude:
          - laravel: 6.*
            php: 7.1
          - laravel: 6.*
            php: 8.1
          - laravel: 6.*
            php: 8.2
          - laravel: 7.*
            php: 7.1
          - laravel: 7.*
            php: 8.1
          - laravel: 7.*
            php: 8.2
          - laravel: 8.*
            php: 7.1
          - laravel: 8.*
            php: 7.2
          - laravel: 8.*
            php: 8.2
          - laravel: 9.*
            php: 7.1
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4
          - laravel: 10.*
            php: 7.1
          - laravel: 10.*
            php: 7.2
          - laravel: 10.*
            php: 7.3
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: '8.0'

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: mbstring
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Installed dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit --exclude-group skipped
