name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3]
        include:
          - php: 8.1
            laravel: 9.*
            testbench: 7.*
          - php: 8.2
            laravel: 10.*
            testbench: 8.*
          - php: 8.3
            laravel: 11.*
            testbench: 9.*

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: mbstring
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Installed dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit --exclude-group skipped
